spring:
  application:
    name: chirp

  datasource:

    url: jdbc:postgresql://db.oeonirnqabvnhxgkpxgg.supabase.co:5432/postgres
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 12000000
      validation-timeout: 5000
      pool-name: HikariCP
      data-source-properties:
        prepareThreshold: 5
        prepareStatementCacheQueries: 256
        prepareStatementCacheSizeMiB: 5

        tcpKeepAlive: true
        socketTimeout: 30
        connectTimeout: 10

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true

jwt:
  secret: ${JWT_SECRET}

chirp:
  email:
    verification:
      expiry-hours: 24
    password-reset:
      expiry-minutes: 30
