spring:
  application:
    name: chirp

  data:
    redis:
      host: "redis-14720.c93.us-east-1-3.ec2.redns.redis-cloud.com"
      password: ${REDIS_PASSWORD}
      username: default
      port: 14720
      connect-timeout: 5000ms
      timeout: 2000ms

  datasource:

    url: jdbc:postgresql://db.oeonirnqabvnhxgkpxgg.supabase.co:5432/postgres
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 12000000
      validation-timeout: 5000
      pool-name: HikariCP
      data-source-properties:
        prepareThreshold: 5
        prepareStatementCacheQueries: 256
        prepareStatementCacheSizeMiB: 5

        tcpKeepAlive: true
        socketTimeout: 30
        connectTimeout: 10

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true

jwt:
  secret: ${JWT_SECRET}

chirp:
  email:
    verification:
      expiry-hours: 24
    password-reset:
      expiry-minutes: 30

nginx:
  trusted-ips:
    - "127.0.0.1"
    - "::1"
    - "172.17.0.0/16"
    - "10.0.0.5/32"